# Generated by Django 2.2.7 on 2019-12-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191218_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
