# Generated by Django 2.2.7 on 2019-12-27 11:55

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('articles', '0003_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('fiction', 'Fiction'), ('non_fiction', 'Non Fiction'), ('technology', 'Technology'), ('lifestyle', 'Lifestyle')], max_length=20, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified_on',
            field=models.DateField(auto_now=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_on',
            field=models.DateField(auto_now_add=True, verbose_name='Published on'),
        ),
    ]
